# =============================================================================
#  figure_s8_network_robustness.py
#  Supplementary Figure S8 — Leaf-Root Network Architecture is Invariant
#  Across Analytical Threshold Choices
#  TPC-2025-1173
#
#  Script location : <project_root>/rivision_pack_1/
#  Output location : <data_root>/output/revision_pack/figures/
#
#  DATA SOURCES (generated by network_robustness.py)
#  ---------------------------------------------------
#  Supp_Table_S1_WheatNetworkSensitivity_Metrics.csv
#    columns: vip_threshold, rho_threshold, tissue, genotype,
#             density, modularity_louvain, transitivity, ...
#    40 rows: 2 VIP × 5 rho × 2 tissues × 2 genotypes
#
#  Supp_Table_S2_WheatNetworkSensitivity_HubJaccard.csv
#    columns: vip_threshold, rho_threshold, genotype,
#             hub_jaccard_leaf_vs_root, ...
#    20 rows: 2 VIP × 5 rho × 2 genotypes
#
#  NOTE: Both files sit in output/revision_pack/ (NOT in the figures subfolder)
# =============================================================================

import os, sys, warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
from matplotlib.lines import Line2D
warnings.filterwarnings("ignore")
matplotlib.rcParams.update({
    "pdf.fonttype": 42, "ps.fonttype": 42,
    "font.family": "DejaVu Sans",
    "axes.spines.top": True, "axes.spines.right": True,
})

# =============================================================================
#  PATHS — USER CONFIGURATION: update these paths for your local environment
# =============================================================================

DATA_DIR   = r"C:\Users\USER\Desktop\data_chem_3_10\output\revision_pack"
OUTPUT_DIR = r"C:\Users\USER\Desktop\data_chem_3_10\output\revision_pack\figures"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# =============================================================================
#  LOAD DATA
# =============================================================================

metrics_csv = os.path.join(DATA_DIR, "Supp_Table_S1_WheatNetworkSensitivity_Metrics.csv")
jaccard_csv = os.path.join(DATA_DIR, "Supp_Table_S2_WheatNetworkSensitivity_HubJaccard.csv")

for p in [metrics_csv, jaccard_csv]:
    if not os.path.isfile(p):
        sys.exit(
            f"[ERROR] File not found:\n  {p}\n"
            f"Run network_robustness.py first:\n"
            f"  python network_robustness.py "
            f"--data-root <data_root> "
            f"--out output/revision_pack"
        )

mdf = pd.read_csv(metrics_csv)
jdf = pd.read_csv(jaccard_csv)

# Normalise column names
mdf.columns = [c.strip() for c in mdf.columns]
jdf.columns = [c.strip() for c in jdf.columns]

# Ensure numeric types
for col in ["vip_threshold", "rho_threshold", "density",
            "modularity_louvain", "transitivity"]:
    if col in mdf.columns:
        mdf[col] = pd.to_numeric(mdf[col], errors="coerce")

for col in ["vip_threshold", "rho_threshold", "hub_jaccard_leaf_vs_root"]:
    if col in jdf.columns:
        jdf[col] = pd.to_numeric(jdf[col], errors="coerce")

print(f"[OK] Metrics CSV: {len(mdf)} rows")
print(f"     VIP thresholds:  {sorted(mdf['vip_threshold'].unique())}")
print(f"     rho thresholds:  {sorted(mdf['rho_threshold'].unique())}")
print(f"     tissues:         {sorted(mdf['tissue'].unique())}")
print(f"     genotypes:       {sorted(mdf['genotype'].unique())}")
print(f"\n[OK] Jaccard CSV: {len(jdf)} rows")

# Primary threshold values (used for row-2 slice + reference lines)
PRIMARY_RHO = 0.70
PRIMARY_VIP = 1.0

# Row 1: at VIP=1.0, sweep rho
row1 = mdf[mdf["vip_threshold"] == PRIMARY_VIP].copy()
row1_jacc = jdf[jdf["vip_threshold"] == PRIMARY_VIP].copy()

# Row 2: at rho=0.70, compare VIP=0.8 vs VIP=1.0
row2 = mdf[mdf["rho_threshold"] == PRIMARY_RHO].copy()

# Sanity check: asymmetry holds in every combination?
n_total = 0; n_leaf_denser = 0; n_root_modular = 0
for _, leaf_row in mdf[mdf["tissue"] == "Leaf"].iterrows():
    partner = mdf[
        (mdf["vip_threshold"] == leaf_row["vip_threshold"]) &
        (mdf["rho_threshold"]  == leaf_row["rho_threshold"]) &
        (mdf["genotype"]       == leaf_row["genotype"]) &
        (mdf["tissue"]         == "Root")
    ]
    if not partner.empty:
        n_total += 1
        if leaf_row["density"] > partner.iloc[0]["density"]:
            n_leaf_denser += 1
        if partner.iloc[0]["modularity_louvain"] > leaf_row["modularity_louvain"]:
            n_root_modular += 1

print(f"\n[SANITY] Leaf denser than Root: {n_leaf_denser}/{n_total} combinations")
print(f"[SANITY] Root more modular than Leaf: {n_root_modular}/{n_total} combinations")
print("\n[OK] Building figure...\n")

# =============================================================================
#  PALETTE  (manuscript identity — design brief)
# =============================================================================

# Tissue × genotype lines
STYLE = {
    ("Leaf", "G1"): {"col": "#3CB371", "ls": "-",  "marker": "o", "ms": 7, "lw": 2.2},
    ("Leaf", "G2"): {"col": "#2AA9B0", "ls": "--", "marker": "s", "ms": 7, "lw": 2.0},
    ("Root", "G1"): {"col": "#2E8B57", "ls": "-",  "marker": "^", "ms": 8, "lw": 2.2},
    ("Root", "G2"): {"col": "#1B6F75", "ls": "--", "marker": "D", "ms": 7, "lw": 2.0},
}
JACCARD_STYLE = {
    "G1": {"col": "#3A6EA5", "ls": "-",  "marker": "o", "ms": 8, "lw": 2.2},
    "G2": {"col": "#7BAEC8", "ls": "--", "marker": "s", "ms": 7, "lw": 2.0},
}

REF_COL   = "#999999"    # primary threshold reference line
CORAL     = "#DC6B4A"    # annotations
NULL_OUTER = "#C6E8FA"   # light blue band
NULL_INNER = "#BDFF7A"   # yellow-green band
ANNO_BG   = "#FFFFFF"
ANNO_EC   = "#AAAAAA"
GRID_COL  = "#DDDDDD"

TAG = 21; SUB = 13; AXT = 12; TCK = 10; LEG = 10; ANN = 9

# =============================================================================
#  HELPERS
# =============================================================================

def spine_style(ax, bg="white"):
    for s in ax.spines.values():
        s.set_linewidth(0.8); s.set_color("black")
    ax.yaxis.grid(True, alpha=0.28, lw=0.5, color=GRID_COL, ls="-")
    ax.xaxis.grid(False); ax.set_axisbelow(True)
    ax.tick_params(labelsize=TCK, length=3, width=0.6)
    ax.set_facecolor(bg)

def ptag(ax, tag, x=-0.14, y=1.05):
    ax.text(x, y, tag, transform=ax.transAxes,
            fontsize=TAG, fontweight="normal", va="bottom", ha="left",
            path_effects=[pe.withStroke(linewidth=2.5, foreground="white")])

def abox(ax, x, y, txt, ha="right", va="top", fs=ANN,
         bold=False, col="#333333", ec=ANNO_EC):
    ax.annotate(txt, xy=(x, y), xycoords=ax.transAxes,
                fontsize=fs, ha=ha, va=va, color=col,
                fontweight="bold" if bold else "normal",
                bbox=dict(boxstyle="round,pad=0.26", fc=ANNO_BG,
                          ec=ec, lw=0.7, alpha=0.95))

def ref_vline(ax, x, label, color=REF_COL, side="right"):
    ax.axvline(x, color=color, ls="--", lw=1.1, alpha=0.75, zorder=2)
    ylim = ax.get_ylim()
    ypos = ylim[0] + (ylim[1]-ylim[0]) * 0.97
    ha = "left" if side == "right" else "right"
    xoff = (ax.get_xlim()[1]-ax.get_xlim()[0]) * 0.015 * (1 if side=="right" else -1)
    ax.text(x + xoff, ypos, label, fontsize=ANN-1, color=color,
            ha=ha, va="top", style="italic")

# =============================================================================
#  FIGURE LAYOUT
#  2 rows × 3 columns, equal panels
# =============================================================================

fig = plt.figure(figsize=(16, 10), dpi=300, facecolor="white")
gs  = gridspec.GridSpec(2, 3, figure=fig,
                         hspace=0.36, wspace=0.34,
                         top=0.93, bottom=0.10,
                         left=0.07, right=0.97)

axes = [[fig.add_subplot(gs[r, c]) for c in range(3)] for r in range(2)]

# Row labels removed — redundant with panel titles

# =============================================================================
#  ROW 1 — |ρ| threshold sweep at VIP = 1.0
# =============================================================================

RHO_VALS = sorted(row1["rho_threshold"].unique())

# ── Panel A — Network Density ────────────────────────────────────────────────
ax = axes[0][0]
spine_style(ax, "#FDFDFB")

# Leaf / Root separation shading — shows which region leaf is above root
leaf_g1 = row1[(row1["tissue"]=="Leaf") & (row1["genotype"]=="G1")].sort_values("rho_threshold")
root_g1 = row1[(row1["tissue"]=="Root") & (row1["genotype"]=="G1")].sort_values("rho_threshold")
ax.fill_between(leaf_g1["rho_threshold"],
                leaf_g1["density"], root_g1["density"],
                color="#3CB371", alpha=0.07, zorder=1,
                label="_nolegend_")

for (tissue, geno), sty in STYLE.items():
    sub = row1[(row1["tissue"]==tissue) & (row1["genotype"]==geno)].sort_values("rho_threshold")
    if sub.empty: continue
    ax.plot(sub["rho_threshold"], sub["density"],
            color=sty["col"], ls=sty["ls"], marker=sty["marker"],
            ms=sty["ms"], lw=sty["lw"],
            markeredgecolor="white", markeredgewidth=0.9,
            zorder=4, label=f"{tissue} {geno}")

ax.set_xlim(RHO_VALS[0]-0.02, RHO_VALS[-1]+0.02)
_ypad = (row1["density"].max() - row1["density"].min()) * 0.18
ax.set_ylim(max(0, row1["density"].min()-_ypad),
            row1["density"].max()+_ypad*2)

ref_vline(ax, PRIMARY_RHO, "Primary\n|ρ|=0.70")
ax.set_xlabel("|ρ| threshold  →  increasing stringency", fontsize=AXT)
ax.set_ylabel("Network density", fontsize=AXT)
ax.set_title("Network Density", fontsize=SUB, fontweight="bold", pad=6)
ptag(ax, "A")

# ── Panel B — Louvain Modularity ─────────────────────────────────────────────
ax = axes[0][1]
spine_style(ax, "#FDFDFB")

root_g1_m = row1[(row1["tissue"]=="Root") & (row1["genotype"]=="G1")].sort_values("rho_threshold")
leaf_g1_m = row1[(row1["tissue"]=="Leaf") & (row1["genotype"]=="G1")].sort_values("rho_threshold")
ax.fill_between(root_g1_m["rho_threshold"],
                root_g1_m["modularity_louvain"],
                leaf_g1_m["modularity_louvain"],
                color="#2E8B57", alpha=0.07, zorder=1)

for (tissue, geno), sty in STYLE.items():
    sub = row1[(row1["tissue"]==tissue) & (row1["genotype"]==geno)].sort_values("rho_threshold")
    if sub.empty: continue
    ax.plot(sub["rho_threshold"], sub["modularity_louvain"],
            color=sty["col"], ls=sty["ls"], marker=sty["marker"],
            ms=sty["ms"], lw=sty["lw"],
            markeredgecolor="white", markeredgewidth=0.9,
            zorder=4, label=f"{tissue} {geno}")

ax.set_xlim(RHO_VALS[0]-0.02, RHO_VALS[-1]+0.02)
_ypad = (row1["modularity_louvain"].max() - row1["modularity_louvain"].min()) * 0.18
ax.set_ylim(max(0, row1["modularity_louvain"].min()-_ypad),
            row1["modularity_louvain"].max()+_ypad*2)

ref_vline(ax, PRIMARY_RHO, "Primary\n|ρ|=0.70")
ax.set_xlabel("|ρ| threshold  →  increasing stringency", fontsize=AXT)
ax.set_ylabel("Modularity Q", fontsize=AXT)
ax.set_title("Louvain Modularity", fontsize=SUB, fontweight="bold", pad=6)
ptag(ax, "B")

# ── Panel C — Hub Jaccard ────────────────────────────────────────────────────
ax = axes[0][2]
spine_style(ax, "#FDFDFB")

# Near-zero band
ax.axhspan(0, 0.06, color=NULL_INNER, alpha=0.45, zorder=1,
           label="Near-zero zone (J < 0.06)")

for geno, sty in JACCARD_STYLE.items():
    sub = row1_jacc[row1_jacc["genotype"]==geno].sort_values("rho_threshold")
    if sub.empty: continue
    ax.plot(sub["rho_threshold"], sub["hub_jaccard_leaf_vs_root"],
            color=sty["col"], ls=sty["ls"], marker=sty["marker"],
            ms=sty["ms"], lw=sty["lw"],
            markeredgecolor="white", markeredgewidth=0.9,
            zorder=4, label=geno)

ax.set_xlim(RHO_VALS[0]-0.02, RHO_VALS[-1]+0.02)
j_max = max(jdf["hub_jaccard_leaf_vs_root"].max(), 0.12)
ax.set_ylim(-0.005, j_max * 1.3)

ref_vline(ax, PRIMARY_RHO, "Primary\n|ρ|=0.70")
ax.set_xlabel("|ρ| threshold  →  increasing stringency", fontsize=AXT)
ax.set_ylabel("Jaccard index  (leaf–root hub overlap)", fontsize=AXT)
ax.set_title("Leaf–Root Hub Overlap (Top-20)", fontsize=SUB, fontweight="bold", pad=6)
ptag(ax, "C")

# ── Row 1 shared legend ──────────────────────────────────────────────────────
leg_r1 = [Line2D([0],[0], color=STYLE[k]["col"], ls=STYLE[k]["ls"],
                  marker=STYLE[k]["marker"], ms=6, lw=1.8,
                  markeredgecolor="white",
                  label=f"{k[0]} {k[1]}")
           for k in STYLE] + [
    Line2D([0],[0], color=REF_COL, ls="--", lw=1.1,
           label="Primary threshold"),
    mpatches.Patch(fc=NULL_INNER, ec="#66AA00", lw=0.7,
                   alpha=0.7, label="Near-zero hub overlap"),
]
fig.legend(handles=leg_r1, loc="lower center",
           bbox_to_anchor=(0.50, 0.005),
           ncol=7, fontsize=LEG, frameon=True,
           framealpha=0.95, edgecolor=ANNO_EC)

# =============================================================================
#  ROW 2 — VIP sensitivity at |ρ| = 0.70
#  VIP sensitivity — simple line plots, NO titles, NO panel letters
# =============================================================================

VIP_VALS = sorted(row2["vip_threshold"].unique())

def vip_line_panel(ax, metric_col, ylabel):
    """4-line slope plot across VIP thresholds.
    No title. No panel letter. No mid-panel tissue labels.
    """
    spine_style(ax, "#FDFDFB")

    vip_x = {v: i for i, v in enumerate(VIP_VALS)}
    x_pos = list(range(len(VIP_VALS)))

    all_vals = row2[metric_col].dropna()
    yspan = all_vals.max() - all_vals.min()
    ypad  = yspan * 0.28
    ax.set_ylim(max(0, all_vals.min() - ypad),
                all_vals.max() + ypad * 1.6)

    for (tissue, geno), sty in STYLE.items():
        sub = row2[(row2["tissue"] == tissue) & (row2["genotype"] == geno)
                   ].sort_values("vip_threshold")
        if sub.empty:
            continue
        xs = [vip_x[v] for v in sub["vip_threshold"]]
        ys = sub[metric_col].values

        ax.plot(xs, ys, color="white", lw=4.5, zorder=3,
                solid_capstyle="round")
        ax.plot(xs, ys, color=sty["col"], ls="-", lw=sty["lw"],
                marker=sty["marker"], ms=sty["ms"] + 1,
                markeredgecolor="white", markeredgewidth=1.0,
                zorder=4)

        # Δ to the right of rightmost point
        if len(ys) == 2:
            delta = ys[-1] - ys[0]
            sign  = "+" if delta >= 0 else ""
            ax.text(xs[-1] + 0.07, ys[-1],
                    f"{sign}{delta:.3f}",
                    fontsize=ANN - 1, color=sty["col"],
                    va="center", ha="left",
                    path_effects=[pe.withStroke(linewidth=1.5,
                                                foreground="white")])

    # Primary VIP reference
    primary_x = vip_x.get(PRIMARY_VIP, len(VIP_VALS) - 1)
    ax.axvline(primary_x, color=REF_COL, ls="--", lw=1.1,
               alpha=0.75, zorder=2)
    ylim = ax.get_ylim()
    ax.text(primary_x + 0.04,
            ylim[0] + (ylim[1] - ylim[0]) * 0.97,
            "Primary\nVIP=1.0",
            fontsize=ANN - 1.5, color=REF_COL,
            ha="left", va="top", style="italic")

    ax.set_xticks(x_pos)
    ax.set_xticklabels([f"VIP \u2265 {v}" for v in VIP_VALS],
                       fontsize=TCK + 1)
    ax.set_xlim(-0.35, len(VIP_VALS) - 0.35)
    ax.set_ylabel(ylabel, fontsize=AXT)
    # intentionally NO set_title() and NO ptag()

vip_line_panel(axes[1][0], metric_col="density",
               ylabel="Network density")
ptag(axes[1][0], "D")
vip_line_panel(axes[1][1], metric_col="modularity_louvain",
               ylabel="Modularity Q")
ptag(axes[1][1], "E")
vip_line_panel(axes[1][2], metric_col="transitivity",
               ylabel="Transitivity")
ptag(axes[1][2], "F")

# Row 2 legend removed — shared with Row 1 legend


# ── Asymmetry count annotation (top right) ───────────────────────────────────


# =============================================================================
#  SAVE
# =============================================================================

pdf_out = os.path.join(OUTPUT_DIR, "Fig_S8_NetworkArchitectureRobustness.pdf")
png_out = os.path.join(OUTPUT_DIR, "Fig_S8_NetworkArchitectureRobustness.png")

fig.savefig(pdf_out, dpi=300, bbox_inches="tight", facecolor="white")
fig.savefig(png_out, dpi=300, bbox_inches="tight", facecolor="white")

print(f"\n{'='*60}")
print(f"  FIGURE S8 COMPLETE")
print(f"  PDF  ->  {pdf_out}")
print(f"  PNG  ->  {png_out}")
print(f"{'='*60}\n")

plt.close(fig)